package com.evsct.app.ui.stats

import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import com.evsct.app.data.prefs.UserUnits
import com.evsct.app.util.Format
import java.io.OutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Render [ui] as a single-page A4 PDF and stream it to [out]. Layout is
 * deliberately text-and-list heavy; the only graphical element is a small
 * bar chart for the monthly cost trend. The caller owns [out] and is
 * responsible for closing it.
 *
 * Page size in points (1/72 in.) — A4 portrait. Coordinates start at the
 * top-left corner.
 */
internal fun writeYearRecapPdf(
    out: OutputStream,
    ui: YearRecapUi,
    units: UserUnits,
) {
    val doc = PdfDocument()
    val pageInfo = PdfDocument.PageInfo.Builder(A4_WIDTH, A4_HEIGHT, 1).create()
    val page = doc.startPage(pageInfo)
    val canvas = page.canvas

    val left = MARGIN
    val right = A4_WIDTH - MARGIN
    val contentWidth = right - left
    var y = MARGIN.toFloat()

    val titlePaint = paint(textSize = 22f, bold = true)
    val subtitlePaint = paint(textSize = 10f, color = Color.DKGRAY)
    val sectionPaint = paint(textSize = 13f, bold = true)
    val labelPaint = paint(textSize = 10f, color = Color.DKGRAY)
    val valuePaint = paint(textSize = 12f, bold = true)
    val bodyPaint = paint(textSize = 11f)
    val footerPaint = paint(textSize = 8.5f, color = Color.GRAY)

    // --- Title block -----------------------------------------------------
    canvas.drawText("EVSCT — ${ui.selectedYear} Recap", left.toFloat(), y + 18f, titlePaint)
    y += 24f
    val genStamp = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault()).format(Date())
    canvas.drawText("Generated $genStamp", left.toFloat(), y + 12f, subtitlePaint)
    y += 24f

    // --- Headlines: 4-column grid (Sessions / Cost / Energy / Distance) --
    drawHeadlines(canvas, left.toFloat(), y, contentWidth.toFloat(), ui, units, labelPaint, valuePaint)
    y += 56f

    // --- Monthly cost bar chart ------------------------------------------
    canvas.drawText("Monthly cost (${ui.costCurrency})", left.toFloat(), y + 12f, sectionPaint)
    y += 20f
    val chartHeight = 130f
    drawMonthlyChart(
        canvas = canvas,
        x = left.toFloat(),
        y = y,
        width = contentWidth.toFloat(),
        height = chartHeight,
        values = ui.monthlyCost.map { it.second },
        labels = ui.monthlyCost.map { it.first },
        barColor = Color.parseColor("#2E7D32"),  // EV green
    )
    y += chartHeight + 16f

    // --- Top brands ------------------------------------------------------
    if (ui.topBrands.isNotEmpty()) {
        canvas.drawText("Top brands by spend (${ui.costCurrency})", left.toFloat(), y + 12f, sectionPaint)
        y += 20f
        ui.topBrands.forEach { (brand, amount) ->
            canvas.drawText(brand, left.toFloat(), y + 11f, bodyPaint)
            val moneyText = Format.money(amount, ui.costCurrency)
            val w = bodyPaint.measureText(moneyText)
            canvas.drawText(moneyText, right - w, y + 11f, bodyPaint)
            y += 14f
        }
        y += 8f
    }

    // --- Longest trip ----------------------------------------------------
    ui.longestTrip?.let { trip ->
        canvas.drawText("Longest trip", left.toFloat(), y + 12f, sectionPaint)
        y += 20f
        canvas.drawText(trip.name, left.toFloat(), y + 11f, bodyPaint)
        y += 14f
        val parts = buildList {
            add(Format.distance(trip.distanceKm, units.useMiles))
            add("${trip.sessionCount} session" + if (trip.sessionCount == 1) "" else "s")
            if (trip.totalCost != null && trip.currency != null) {
                add(Format.money(trip.totalCost, trip.currency))
            }
        }
        canvas.drawText(parts.joinToString(" · "), left.toFloat(), y + 11f, labelPaint)
        y += 18f
    }

    // --- Footer ----------------------------------------------------------
    val footerY = (A4_HEIGHT - MARGIN).toFloat()
    canvas.drawText(
        "Generated by EVSCT. ${ui.sessionCount} sessions in ${ui.selectedYear}." +
            if (ui.excludedByCurrency > 0) {
                " (${ui.excludedByCurrency} session" +
                    (if (ui.excludedByCurrency == 1) "" else "s") +
                    " in another currency excluded from cost.)"
            } else "",
        left.toFloat(),
        footerY,
        footerPaint,
    )

    doc.finishPage(page)
    doc.writeTo(out)
    doc.close()
}

/* --- private layout helpers --- */

private fun drawHeadlines(
    canvas: android.graphics.Canvas,
    x: Float, y: Float, width: Float,
    ui: YearRecapUi,
    units: UserUnits,
    labelPaint: Paint,
    valuePaint: Paint,
) {
    val cells = listOf(
        "Sessions" to ui.sessionCount.toString(),
        "Total cost" to Format.money(ui.totalCost, ui.costCurrency),
        "Total energy" to Format.kwh(ui.totalKwh),
        "Distance" to Format.distance(ui.totalDistanceKm, units.useMiles),
    )
    val cellWidth = width / cells.size
    cells.forEachIndexed { i, (label, value) ->
        val cx = x + i * cellWidth
        canvas.drawText(label, cx, y + 12f, labelPaint)
        canvas.drawText(value, cx, y + 30f, valuePaint)
    }
}

private fun drawMonthlyChart(
    canvas: android.graphics.Canvas,
    x: Float, y: Float, width: Float, height: Float,
    values: List<Double>,
    labels: List<String>,
    barColor: Int,
) {
    val n = values.size
    if (n == 0) return
    val maxValue = (values.maxOrNull() ?: 0.0).coerceAtLeast(1.0)
    // Reserve bottom strip for month labels.
    val labelStripHeight = 12f
    val plotHeight = height - labelStripHeight
    val baseY = y + plotHeight

    // Fixed gap between bars (in points). Bar width = remaining space / n.
    val gap = 4f
    val barWidth = ((width - (n - 1) * gap) / n).coerceAtLeast(1f)

    val barPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = barColor }
    val axisPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
        color = Color.LTGRAY
        strokeWidth = 0.5f
    }
    val labelPaint = paint(textSize = 8f, color = Color.DKGRAY).apply {
        textAlign = Paint.Align.CENTER
    }

    // Baseline.
    canvas.drawLine(x, baseY, x + width, baseY, axisPaint)

    values.forEachIndexed { i, v ->
        val cx = x + i * (barWidth + gap)
        val barH = ((v / maxValue) * plotHeight).toFloat().coerceAtLeast(0f)
        if (v > 0) {
            canvas.drawRect(cx, baseY - barH, cx + barWidth, baseY, barPaint)
        }
        canvas.drawText(labels[i], cx + barWidth / 2f, baseY + 10f, labelPaint)
    }
}

private fun paint(
    textSize: Float = 11f,
    bold: Boolean = false,
    color: Int = Color.BLACK,
): Paint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
    this.textSize = textSize
    this.color = color
    if (bold) typeface = android.graphics.Typeface.DEFAULT_BOLD
}

/** A4 portrait at 72 dpi. */
private const val A4_WIDTH = 595
private const val A4_HEIGHT = 842
private const val MARGIN = 36
